spring:
  application:
    name: resume-ai-analyzer

  datasource:
    url: jdbc:postgresql://localhost:5432/resume_builder
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

gemini:
  api:
    key: ${GEMINI_API_KEY:}

chroma:
  endpoint: ${CHROMA_ENDPOINT:http://localhost:8000}
  collection:
    name: resume_chunks

jwt:
  secret: ${JWT_SECRET:mySuperSecretKeyForJwtAuthenticationProject123456789}
