spring:
  application:
    name: resume-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/resume_builder
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

gemini:
  api:
    key: ${GEMINI_API_KEY}

chroma:
  endpoint: ${CHROMA_ENDPOINT:http://localhost:8000}
  collection:
    id: df2459e4-7b93-4ebb-867a-5bcf6b4f9438